branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '10'
- '12'
matrix:
  allow_failures:
  - node_js: '12'
before_install:
- mkdir cvc4/
- wget https://almond-static.stanford.edu/test-data/cvc4-1.6-x86_64-linux-opt -O cvc4/cvc4
- chmod +x cvc4/cvc4
- export PATH="`pwd`/cvc4:$PATH"
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
env:
  global:
  - COVERALLS_PARALLEL=true
  - secure: Zq1EuaT8hx7hVrKygiAlCIjsNMOWVf+/68Ce5TgZc2+dg5gAAeLUkuEyvFswD3yfpCf8s3FtQBubwOFz0y1cNsAzUGUrJqPLeSUnuB47IzKvtV9MK8gh1fN/AOHRH0L6tMTWs8aXKzS9U8uhBLH8PNKUoukbwqUhNlfzNGyxC8eOq6mwkIeSKNqRW0Wckd+gjLJtXhNTJlKDfhWjdMkzh0SOThhT1K0yj2DiMUT4nQO4IxvsFYa1YfQU70MkJxgpFQ5EavqThwKRUqxnMgOYkpGDD2FgasG9ZI/yp1B3ukq/bwhe9FqvYoEpvNIHk7ggx7w13QzrB0AkaxEqzayOYLS6TjL+X8c8eTuNved3+uNh8Q9wxTnpZemlOBSxOuSZMLRl89yuDSl0aSLZ1jt3h7YVHJpszWNGcpF+kfWe4zDx83rdS61nZQC2b11WfOixapddGohlSmGXx4/cuzAYaFGssLt4OBo1mKPco8I9PiUZOTjx3PVk3UqzoDrrxRf0aK7WPFfG6EafXeuQOepxJsvTYss3+GdCl5oCsLk3As+BTkie5h3d+yDEk6E7nVZaeGcTQKSYFL/6OR0xBaraVmynL6I4EEF2IG/umJB2pM1QOni53PC5C6jFynAPNa9f6v75BZ2pEXjg1E0k93RztjXCU4EaRkDxrz+aNon0Lyk=
notifications:
  webhooks: https://coveralls.io/webhook
  slack:
    secure: otIAjzXOCyKKXjeZ6azjxmfjVK5v9ziFuADWTQdgRlJUTNxu2YdJ8GX6ukWXxNAtR7v1cZxihZZi30y+dsmV6cocJqiZCLHwTDKTHHCzKzBjRq5OzfA6pfsyWqT3xGvuCM1v+U6BPLUQI56+jeUeb9pmJOwl8ac5CDXHi9StAu8B4XKNF/kGldLcsPGfFomVPGj5PzsZnp4phIDYc5UjPleRR+N9df+nAZaMRCR/hIRLtrsYRWuOeIAX9q+xovsx2ccrHBlsegu0ToTqFEZFIBXpHFGv9bDqc0kuizNTGM+d+1IPX4TYNurx9Ksbauao0DRuGD+yvPtbD+V8P9Jw+uslTam4D6WgLDfT1Jjk4wbN3OtKssYFmiwtLUGO/Up113MO5kNK1wpQRtRnDu59Rg0bOrpkdkB1t+SQ9KvJbYyRhu+42zw3qgSM29RRAuNIbHb7L4PZILzOieau8uDoQIOYWbYV47weK4/1/0zhQoF37+4TEqmkPI3jTcypgCUrqwdtuqOnD/EkoZVcg2EtttB/VahXmQO9cDZ0AX3GuVao7WFldrXKM8j+RPV6xaCj/RYO/6XZEkrgPFTF3rogCaw898VZ1AZvQqFgIcDyWsWpc9bzMVLDWHg4YMyTOQith/qLNeG3/EXPjofO3FmpqfaF3YuBjzD1SKEqgoa0Az8=
deploy:
  provider: npm
  email: gcampagn@cs.stanford.edu
  skip_cleanup: true
  api_key:
    secure: gc/zEzNZbLBtOXZJyezUqL+ht7JHQi+zIDYho4VKzc8U/8WZDwXYPmN5Qw6UO6vMGVETEcYy+nAdqE9TFutDtod7Ov6dk+IxSMFNUKiGQLASHhKyWylkaF8V9xao2Sso7MfYl9uMqfm1UTJHeWzJneY9eJc4r9W6T20w7YatTfjGuCtsSfRDtlsPKdyGoGno8BejfvGC05rUQpNegP6X7jkUJ1Hn/r5z6ZEVlQSfBucCCLQUyzB2NLXkFhPzYhaLPko+98qx5rIPbE2eyJU2TDusNpViV20aeVt7gI4O47gu49tpxoqoRpv8CY05eljGekVyi9K062KSLZnd0Td2GsY9y1vpu0PMPzNirCxY61cNrYoO8IHFHMnnejiTmTxq2oGrrNRQHK4t7CdOK7MmlxAH+Q5+DPGb5RE1ZGVeHjaLKc5jpLfAdp3cRUtkywR/wrPNF+eYFPdXeSCnfVcBfxjQFK0avT+a2jYTCfy7GCk+FZgaAcFlflr8pzXlLJsGM8cN/ld5X2FmMKAFpT1uZbV+VjFT1snwuRxOW9WJgDHeXH1fs8ufAeEyyleFt7rxsOyroEnASFNkSjJNQHxeaoNxQM8+LAVnOCjtrASlYq2a42251coSaBcHs6uTo6kcuK9JAxNIsQ4tHxcrQlV5smRz9ET8qp9w7IIJwTdMRDc=
  on:
    tags: true
    repo: stanford-oval/thingtalk
